### ISSUE TITLE
Size counter not reset when clear()

### ISSUE THREAD

**Issue by Zhiyuan-Wu** [Eric-Canas/CircularDict#1]
The attribute, CircularDict.current_size, is not properly reset upon the clear() call. This may lead to incorrect pop. As an example, this code throws an exception 'KeyError: 'dictionary is empty'':
```python
from circular_dict import CircularDict
a = CircularDict(maxsize_bytes=60)
a[1] = 1
a.clear()
a[2] = 2
```
Thanks.

**Comment by Eric-Canas** [comment]
Sorry, you were true :(

I was not properly updating `CircularDict.current_size` when clearing the dict, leading to inconsistencies.

I patched it right now. As far as I have tested, everything should work ok now. 

You can update it with `pip install --upgrade circular-dict` 

Thanks a lot for finding that bug!

**Comment by Zhiyuan-Wu** [comment]
Thank you very much, it works and really helps me.
