### ISSUE TITLE
Ensuring Thread Safety: Implementing Synchronization Mechanisms 

### ISSUE THREAD

**Issue by keshavrkaranth** [Eric-Canas/CircularDict#3]
Currently, the set, delete, and other methods are not equipped with thread locks. In a multi-threaded environment, this could lead to unexpected race conditions. Implementing proper thread synchronization mechanisms in these methods would ensure the stability and reliability of the code.

**Comment by Eric-Canas** [comment]
Hi! You are True.

I didn't take it into account. 

I'll implement it!

Thanks!

**Comment by Eric-Canas** [comment]
Implemented and updated at [PyPi](https://pypi.org/project/circular-dict/1.9/)

You can update it with `pip install --upgrade circular-dict`

Thanks for the proposal!

Please, reopen the issue if you find any problem =^~^=

**Comment by keshavrkaranth** [comment]
Thanks for Implementing it.BTW I have already implemented the lock in the code and using it.
